### ISSUE TITLE
Problems with pom in 'javax.mail:javax.mail-api:1.5.4'

### ISSUE THREAD

**Issue by pskiwi** [jk1/Gradle-License-Report#2]
Hi,
the plugin fails on the dependency `javax.mail:javax.mail-api:1.5.4`.

The problem is caused by the file:
`javax.mail-1.5.4.jar\META-INF\maven\com.sun.mail\javax.mail\pom.xml`

the problematic section is:
```
<compilerArguments>
	<Xlint:all/>
	<Xlint:-rawtypes/>
	<Xlint:-unchecked/>
       <Xlint:-finally/>
</compilerArguments> 
```
Gradle stops with
```
...
Caused by: org.xml.sax.SAXParseException; lineNumber: 116; columnNumber: 17; The prefix "Xlint" for element "Xlint:all" is not bound.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
        at com.github.jk1.license.reader.PomReader.slurpPomFromZip(PomReader.groovy:85)
        at com.github.jk1.license.reader.PomReader.this$2$slurpPomFromZip(PomReader.groovy)
        at com.github.jk1.license.reader.PomReader$this$2$slurpPomFromZip$1.callCurrent(Unknown Source)
        at com.github.jk1.license.reader.PomReader.slurpPom(PomReader.groovy:71)
        at com.github.jk1.license.reader.PomReader.this$2$slurpPom(PomReader.groovy)
        at com.github.jk1.license.reader.PomReader$this$2$slurpPom$0.callCurrent(Unknown Source)
        at com.github.jk1.license.reader.PomReader.readPomData(PomReader.groovy:25)
        at com.github.jk1.license.reader.PomReader$readPomData.call(Unknown Source)
        at com.github.jk1.license.reader.ModuleReader$_read_closure1.doCall(ModuleReader.groovy:24)
        at com.github.jk1.license.reader.ModuleReader.read(ModuleReader.groovy:21)
        at com.github.jk1.license.reader.ModuleReader$read.call(Unknown Source)
        at com.github.jk1.license.reader.ConfigurationReader.read(ConfigurationReader.groovy:30)
        at com.github.jk1.license.reader.ConfigurationReader$read.call(Unknown Source)
        at com.github.jk1.license.reader.ProjectReader.read(ProjectReader.groovy:45)
        at com.github.jk1.license.reader.ProjectReader$read.call(Unknown Source)
        at com.github.jk1.license.task.ReportTask.generateReport(ReportTask.groovy:21)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        ... 76 more
```

tested with 
- plugin '0.3.1' 
- Gradle 2.5
- Java 1.8.51

Workaround:
```
licenseReport {
   excludeGroups = ['com.sun.mail'] 
}
```

**Comment by jk1** [comment]
I suppose it's `com.sun.mail:javax.mail:1.5.4 `, not `javax.mail:javax.mail-api:1.5.4`. The latter one's pom contains no xlint-namespaced sections. Still, there's definitely a problem to fix.
