### ISSUE TITLE
Output dir uses different base pathes

### ISSUE THREAD

**Issue by Burtan** [jk1/Gradle-License-Report#277]
Hey,

the task using the parameter outputDir uses different base pathes. The output dir gets generated using the base path of the gradlew file, the file that is created by the renderer, that should be located inside the output dir uses the base path of the subproject. Thus when running the license reporting task from a subdir, you can get error messages that the rendered file cannot be created because the path does not exist.

You want a PR?

A workaround is to use
`outputDir = File("relativePath").absolutePath`

**Comment by chadlwilson** [comment]
This change (or something else in `2.7`) seemed to break a previous multi-project setup which was otherwise working OK, which is very confusing. Really no idea what changed, but during `:subproject:generateLicenseReport`, started getting errors like the below looking at an output path in the root project. Not quite sure why, maybe due to trying to read the `outputDir` after the fact for a dependent task and interpreting its relative path differently :-/

```
Caused by: java.io.FileNotFoundException: /path/to/root-project/build/reports/dependency-license/THIRD-PARTY-NOTICES.txt (No such file or directory)
        at org.gradle.internal.classpath.declarations.GroovyDynamicDispatchInterceptors.intercept_setProperty(GroovyDynamicDispatchInterceptors.java:95)
        at com.github.jk1.license.render.TextReportRenderer.render(TextReportRenderer.groovy:49)
        at com.github.jk1.license.render.ReportRenderer$render.call(Unknown Source)
        at com.github.jk1.license.task.ReportTask$_generateReport_closure6.doCall$original(ReportTask.groovy:73)
        at com.github.jk1.license.task.ReportTask$_generateReport_closure6.doCall(ReportTask.groovy)
```
