### ISSUE TITLE
Ambigous method error with 0.3.15

### ISSUE THREAD

**Issue by jacek99** [jk1/Gradle-License-Report#30]
I integrated 0.3.15 (with the new InventoryHtmlReporter) into out of our builds, worked perfectly, no issues.

Added it to another, more complex project...failed to run

```
:myproject:generateLicenseReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myproject:generateLicenseReport'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
```

Linux, Gradle Wrapper 4.0, Java 8

Build file config:
```
    licenseReport {
        renderer = new com.github.jk1.license.render.InventoryHtmlReportRenderer('third-party-license-report.html')
    }
```

**Comment by jacek99** [comment]
Verified am on the right version:
```
\--- gradle.plugin.com.github.jk1:gradle-license-report:0.3.15
```

**Comment by jacek99** [comment]
I removed the licenseReport.renderer to run just with the default renderer and the same issue occurred.
So it does not seem to be related to the new InventoryHtmlReportRenderer per say.

**Comment by jacek99** [comment]
I also downgraded it to 0.3.14 and the issue is still there. So it does not appear to be regression in 0.3.15

**Comment by jacek99** [comment]
Exact stack trace:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myproject:generateLicenseReport'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
        at com.github.jk1.license.LicenseReportPlugin$LicenseReportExtension.beforeExecute(LicenseReportPlugin.groovy:62)
        at com.github.jk1.license.LicenseReportPlugin$LicenseReportExtension$beforeExecute.call(Unknown Source)
        at com.github.jk1.license.task.ReportTask.generateReport(ReportTask.groovy:20)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
```

**Comment by jacek99** [comment]
I think for whatever reason the entire LicensePllugin.afterEvaluate block never gets called.
Even if I explicitly define the outputDir (since that is the root cause of this, it is null),
then it generates a null report, with no libraries.

Looks like none of the properties defined in afterEvaluate ever get initialized.

Don't know much about how Gradle plugins work, so this is as far as I can take it to help you :-/

**Comment by jacek99** [comment]
Here's a screenshot of the null report. I presume it is because of the importers being empty, which once again points to afterEvaluate never getting executed during the build lifecycle.

![null_report](https://user-images.githubusercontent.com/36376/31035275-04702f64-a52d-11e7-851a-e99fe963d5ce.png)

**Comment by jk1** [comment]
@jacek99, not sure about that. Empty importer set is a valid use case and it works for me.
Please try to specify outputDir explicitly, let's see if it helps: 

    licenseReport {
        renderer = new com.github.jk1.license.render.InventoryHtmlReportRenderer('third-party-license-report.html')
        outputDir = "${project.buildDir}/reports/dependency-license"
     }

**Comment by jacek99** [comment]
Sure, I do that. That I just get the "null" report (see screenshot above).

It looks like none of the variables you set up in LicensePlugin.afterEvaluate get initialized.

For all I know this could be a Gradle bug.
Can you try and follow up with them?

I have one repo where this works fine. All I have to do is define licenseReport.renderer in build.gradle and all is good.

Then it 2 other repos I do the same and I get the error above, with the exact same version of the plugin.

So something is definitely off.

**Comment by jk1** [comment]
I see, thanks. It may be a Gradle bug indeed. The other possible cause is that your build triggers task execution during configuration phase, which is not impossible to achieve.

Check out 0.3.16. I got rid of afterEvaluate build hook at all, as it was not really necessary anyway.

**Comment by jacek99** [comment]
Tested with 0.3.16, definitely better, generates the report now.
The only glitch left is that it seems to still display "null" as title in  both panes, see attachment
![0316](https://user-images.githubusercontent.com/36376/31085904-015bf8d4-a75e-11e7-94c4-64cad97acb07.png)

**Comment by jk1** [comment]
Adding an explicit title may help:

````renderer = new InventoryHtmlReportRenderer('third-party-license-report.html', 'Project Dependencies')````

I'll put a default of some sort there to avoid further confusion.

**Comment by jacek99** [comment]
Yup that worked fine.
We're good, thanks!
