### ISSUE TITLE
Throwing exceptions during report generation looking for non-existent dependencies

### ISSUE THREAD

**Issue by jacek99** [jk1/Gradle-License-Report#35]
In our corporate environment, we cannot point to Maven Central, so we point all of our Gradle builds to a local Artifactory with just approved libraries that passed legal license reviews.

On one of our projects we get multiple exceptions during the report generation ```./gradlew my-service:generateLicenseReport```, e.g.
```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.apache.axis2:axis2-parent:1.4.1.
Required by:
    project :my-service
        at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:38)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:105)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:60)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:93)
        at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:45)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ComponentState.resolve(DependencyGraphBuilder.java:854)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ComponentState.getMetaData(DependencyGraphBuilder.java:865)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.calculateTargetConfigurations(DependencyGraphBuilder.java:446)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.attachToTargetConfigurations(DependencyGraphBuilder.java:417)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.attachToTargetRevisionsSerially(DependencyGraphBuilder.java:223)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:213)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:148)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:121)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:86)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:138)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:73)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$4.run(DefaultConfiguration.java:469)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:461)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:437)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:429)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor282.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
        ... 100 more
```

But that dependency is not defined in our list.
I can prove it by scanning for it:
```
./gradlew my-service:dependencies | grep axis2-parent
```
Nothing shows up.

We have the same problem for yet another library:
```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.sun.codemodel:codemodel-project:2.6.
Required by:
    project :my-service
        at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:38)
```
Once again, ```com.sun.codemodel:codemodel-project``` is nowhere to be found in the dependencies for our entire project. So no idea why the plugin is trying to look for it. Since the build points to Artifactory, those libraries are not there (further proof that we do not depend on them...our build machines are locked down from Internet and can only pull libs from Artifactory, due to SOC2 regulations).

I tried excluding both of these:
```
excludes = ['org.apache.axis2:axis2-parent','com.sun.codemodel:codemodel-project']
```
made no difference. The excludes got ignored. Still same error.

This is 0.3.16, using Gradle Wrapper 4.0

**Comment by jacek99** [comment]
Looking at the output in debug mode, it looks like it's picking up the runtime dependency of a different module
```
11:58:56.955 [DEBUG] [com.github.jk1.license.task.ReportTask] Processing dependency: com.sun.xml.bind:jaxb-xjc:2.2.7;runtime
11:58:56.955 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'jaxb-xjc.jar (com.sun.xml.bind:jaxb-xjc:2.2.7)' in resolver cache: /home/jfurmank/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-xjc/2.2.7/f351eed8b1ee9a1dd242bf81bf7a391c40a16d18/jaxb-xjc-2.2.7.jar
11:58:56.955 [INFO] [com.github.jk1.license.task.ReportTask] Processing artifact: jaxb-xjc.jar (com.sun.xml.bind:jaxb-xjc:2.2.7) (/home/jfurmank/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-xjc/2.2.7/f351eed8b1ee9a1dd242bf81bf7a391c40a16d18/jaxb-xjc-2.2.7.jar)
11:58:56.955 [DEBUG] [com.github.jk1.license.task.ReportTask] Processing pom from archive: /home/jfurmank/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-xjc/2.2.7/f351eed8b1ee9a1dd242bf81bf7a391c40a16d18/jaxb-xjc-2.2.7.jar
11:58:56.956 [DEBUG] [com.github.jk1.license.task.ReportTask] Searching for POM file in /home/jfurmank/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-xjc/2.2.7/f351eed8b1ee9a1dd242bf81bf7a391c40a16d18/jaxb-xjc-2.2.7.jar -- found META-INF/maven/com.sun.codemodel/codemodel/pom.xml
11:58:56.957 [DEBUG] [com.github.jk1.license.task.ReportTask] POM content children: [modelVersion, groupId, artifactId, version, name, description, parent, dependencies]
11:58:56.957 [DEBUG] [com.github.jk1.license.task.ReportTask] Processing parent POM: [groupId, artifactId, version, relativePath]
11:58:56.957 [DEBUG] [com.github.jk1.license.task.ReportTask] Parent to fetch: [group:com.sun.codemodel, name:codemodel-project, version:2.6, ext:pom]
```

I tried to force it to use "compile" configuration only
```
    configurations = ['compile']
```

did not work. Still showing same exceptions.

**Comment by jk1** [comment]
Do these exceptions fail the build or report generation?

**Comment by jacek99** [comment]
No, the report still completes. But all the exceptions logged during the build generated negative feedback amongst team members.

**Comment by jk1** [comment]
I see. I guess I know where failed resolution attempts come from. These are parent declarations present in your dependencies' poms. When looking for a license the plugin may also try to examine a parent artifact, provided one is mentioned in dependency's pom.

**Comment by jacek99** [comment]
Possible. Sounds different than what Ivy / Gradle do, since they seem to skip it.

**Comment by jk1** [comment]
Indeed, gradle does not fetch parents artifact upon dependency resolution.
I can prettify the output if it seems to be a problem.

**Comment by jacek99** [comment]
I guess skipping it altogether would be cleanest.

Also why is the "compile" configuration restriction not respected? Is it the same issue or a separate problem?

**Comment by jk1** [comment]
> I guess skipping it altogether would be cleanest.

I don't think it's reasonable to drop parent lookup at all. There are libraries that defines their license in parent pom only.

> Also why is the "compile" configuration restriction not respected

Currently I see no signs of disrespect. In my understanding the following happens atm: your dependencies are filtered to belong to compile configuration only. After that for each filtered dependency license information analysis is performed, parent lookup included. 

It's exclude logic that may also require a fix here, but configuration filter seems to perform as expected.

**Comment by jacek99** [comment]
Makes sense. Try to look up the parent, if not there, skip it silently (or maybe with an INFO level message).

The compile config stil shows "runtime" config being evaluated, hence my question:
```
11:58:56.955 [DEBUG] [com.github.jk1.license.task.ReportTask] Processing dependency: com.sun.xml.bind:jaxb-xjc:2.2.7;runtime
```

**Comment by jk1** [comment]
0.3.17 should have this annoying exception suppressed. 
As for the configuration filtering I'll investigate that separately.
