### ISSUE TITLE
CachingArtifactResolver searches for non-existing .pom1 files when used within Atlassian Bamboo 

### ISSUE THREAD

**Issue by ManfredSchenkIOSB** [jk1/Gradle-License-Report#44]
When running within Atlassian Bamboo the CachingArtifactResolver searches for (of cause) non-existing .pom1 files and therefore fails the build.

See example:

```
build	22-Feb-2018 10:11:42	10:11:42.923 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of artifact 'logback-parent.pom1 (ch.qos.logback:logback-parent:1.2.3)' in resolver cache
build	22-Feb-2018 10:11:42	10:11:42.924 [DEBUG] [com.github.jk1.license.ReportTask] Failed to retrieve parent artifact [group:ch.qos.logback, name:logback-parent, version:1.2.3, ext:pom1]
build	22-Feb-2018 10:11:42	org.gradle.internal.resolve.ArtifactNotFoundException: Could not find logback-parent.pom1 (ch.qos.logback:logback-parent:1.2.3).
build	22-Feb-2018 10:11:42	Searched in the following locations:
build	22-Feb-2018 10:11:42	     #http://XXX.de/artifactory/XXXX/ch/qos/logback/logback-parent/1.2.3/logback-parent-1.2.3.pom1
build	22-Feb-2018 10:11:42		at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound(DefaultBuildableArtifactResolveResult.java:27)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifactFromCache(CachingModuleComponentRepository.java:324)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:274)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.BaseModuleComponentRepositoryAccess.resolveArtifact(BaseModuleComponentRepositoryAccess.java:65)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedModuleComponentRepository$CachedAccess.resolveArtifact(InMemoryCachedModuleComponentRepository.java:124)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:174)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifact(RepositoryChainArtifactResolver.java:78)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ArtifactResolverChain.resolveArtifact(ComponentResolversChain.java:121)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingArtifactResolver.resolveArtifact(ErrorHandlingArtifactResolver.java:46)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSource.create(DefaultArtifactSet.java:170)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSource.create(DefaultArtifactSet.java:157)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.DefaultResolvedArtifact.getFile(DefaultResolvedArtifact.java:135)
build	22-Feb-2018 10:11:42		at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ResolvableArtifact$getFile.call(Unknown Source)
build	22-Feb-2018 10:11:42		at com.github.jk1.license.util.CachingArtifactResolver.doResolveArtifact(CachingArtifactResolver.groovy:38)

```

When running on the command line it works without errors.

Remark (the artifactory server URL has been partly anonymized by XXXX)

**Comment by ManfredSchenkIOSB** [comment]
It seems that the pom1 String comes from line 121 in PomReader.groovy: `"ext" : "pom1"`

**Comment by ManfredSchenkIOSB** [comment]
Some more information after detailed debugging: The problem arises when the license-check plugin is used in the same build as the OWASP-dependency-check-plugin (https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/). It seems that the CachingArtifactResolver introduces some synthetic artifacts that interfere with the dependeny-check-plugin.

**Comment by jk1** [comment]
> It seems that the pom1 String comes from line 121 in PomReader.groovy: "ext" : "pom1" instroduced with the fix for issue #35

Must be a typo. Thanks for pointing it out.

**Comment by jk1** [comment]
Converted `pom1` back to `pom` in 0.5.1. 
Please give it a try and let me know if it solves the problem.

**Comment by ManfredSchenkIOSB** [comment]
works now with 0.5.1 Thank you for your fast response
